<?php

namespace Tests\Feature\Hr;

use App\Models\Hr\HrCandidate;
use App\Models\Hr\HrEmployee;
use App\Models\Tenant;
use App\Models\User;
use App\Services\Hr\CandidateService;
use App\Support\Hr\ResumeTextExtractor;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

/**
 * Review comment #15 — "ADD CANDIDATE – AUTO FETCH CANDIDATE DETAIL AND
 * (PRESENT CO., DEPT, DESIGNATION, REFERENCE".
 *
 * CandidateAutoFetchTest covers the LinkedIn source. This covers the second one:
 * the RESUME, which is where DEPT and REFERENCE actually live — a public profile
 * states neither.
 *
 * The PDFs here are generated by dompdf and parsed back by smalot/pdfparser, so
 * the round trip is real rather than a string handed straight to the regexes. A
 * hand-fed string would pass even if the extractor returned nothing at all.
 */
class CandidateResumeAutoFetchTest extends TestCase
{
    use RefreshDatabase;

    private const TENANT = 1;

    private User $actor;

    protected function setUp(): void
    {
        parent::setUp();

        Storage::fake('hr_resumes');

        (new Tenant())->forceFill([
            'id' => self::TENANT, 'name' => 'T1', 'slug' => 't1', 'subdomain' => 't1', 'status' => 'active',
        ])->save();

        $this->actor = User::create([
            'tenant_id' => self::TENANT, 'name' => 'HR', 'email' => 'hr'.uniqid().'@test.com',
            'password' => bcrypt('secret'), 'role' => 'admin', 'status' => 'active',
        ]);
    }

    // ── fixtures ───────────────────────────────────────────────────────────

    /** A real PDF, built from HTML, that a parser must actually read. */
    private function resumePdf(array $lines): UploadedFile
    {
        $html = '<html><body>'.implode('', array_map(fn ($l) => '<p>'.$l.'</p>', $lines)).'</body></html>';

        $path = tempnam(sys_get_temp_dir(), 'cv').'.pdf';
        file_put_contents($path, Pdf::loadHTML($html)->output());

        return new UploadedFile($path, 'resume.pdf', 'application/pdf', null, true);
    }

    /** A real .docx — a zip holding word/document.xml. */
    private function resumeDocx(array $lines): UploadedFile
    {
        $body = implode('', array_map(
            fn ($l) => '<w:p><w:r><w:t>'.htmlspecialchars($l, ENT_XML1).'</w:t></w:r></w:p>',
            $lines
        ));

        $path = tempnam(sys_get_temp_dir(), 'cv').'.docx';
        $zip  = new \ZipArchive();
        $zip->open($path, \ZipArchive::CREATE | \ZipArchive::OVERWRITE);
        $zip->addFromString('word/document.xml',
            '<?xml version="1.0"?><w:document xmlns:w="urn:w"><w:body>'.$body.'</w:body></w:document>');
        $zip->close();

        return new UploadedFile($path, 'resume.docx',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document', null, true);
    }

    private function candidate(array $attributes = []): HrCandidate
    {
        return HrCandidate::create(array_merge([
            'tenant_id' => self::TENANT,
            'name'      => 'Rahul Sharma',
            'email'     => 'r'.uniqid().'@test.com',
            'stage'     => 'Applied',
        ], $attributes));
    }

    private function employee(string $name): HrEmployee
    {
        return HrEmployee::create([
            'tenant_id' => self::TENANT, 'name' => $name,
            'employee_code' => 'E'.substr(uniqid(), -6),
            'department' => 'Engineering', 'designation' => 'Engineer',
            'joining_date' => '2020-01-01', 'status' => 'Active',
        ]);
    }

    private const FULL_CV = [
        'RAHUL SHARMA',
        'Company: Acme Technologies Pvt Ltd',
        'Designation: Senior Software Engineer',
        'Department: Platform Engineering',
        'Referred by: Priya Nair',
    ];

    // ── extraction ─────────────────────────────────────────────────────────

    public function test_a_pdf_resume_yields_readable_text(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        $text = ResumeTextExtractor::fromStoredPath($candidate->fresh()->resume_path);

        $this->assertNotNull($text, 'The PDF parser returned nothing for a valid PDF.');
        $this->assertStringContainsString('Platform Engineering', $text);
    }

    public function test_a_docx_resume_yields_readable_text(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumeDocx(self::FULL_CV),
        ])->assertOk();

        $text = ResumeTextExtractor::fromStoredPath($candidate->fresh()->resume_path);

        // Regression: an earlier paragraph regex consumed the '>' of <w:p>, which
        // left strip_tags treating the whole document as one unclosed tag and
        // returning an empty string.
        $this->assertNotNull($text, 'The DOCX reader returned nothing for a valid .docx.');
        $this->assertStringContainsString('Platform Engineering', $text);
        $this->assertStringContainsString('Senior Software Engineer', $text);
    }

    public function test_a_legacy_doc_yields_null_rather_than_a_mangled_string(): void
    {
        // A .doc is a binary OLE container with no dependable pure-PHP reader.
        // Half-decoding it would put rubbish on a candidate's record, so the
        // extractor declines instead.
        Storage::disk('hr_resumes')->put('tenant_1/legacy.doc', random_bytes(512));

        $this->assertNull(ResumeTextExtractor::fromStoredPath('tenant_1/legacy.doc'));
    }

    public function test_a_corrupt_file_is_swallowed_rather_than_thrown(): void
    {
        // A PDF extension over bytes that are not a PDF. The parser will throw;
        // an unreadable resume must not take the upload down with it.
        Storage::disk('hr_resumes')->put('tenant_1/broken.pdf', 'this is not a pdf');

        $this->assertNull(ResumeTextExtractor::fromStoredPath('tenant_1/broken.pdf'));
    }

    public function test_a_missing_file_yields_null(): void
    {
        $this->assertNull(ResumeTextExtractor::fromStoredPath('tenant_1/nope.pdf'));
        $this->assertNull(ResumeTextExtractor::fromStoredPath(null));
    }

    public function test_a_resume_with_no_labelled_fields_changes_nothing(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(['RAHUL SHARMA', 'An engineer who has built payment systems.']),
        ])->assertOk()->assertJsonPath('auto_filled', []);

        // The upload still succeeds and the file is still stored.
        $this->assertNotNull($candidate->fresh()->resume_path);
        $this->assertNull($candidate->fresh()->current_department);
    }

    // ── parsing rules ──────────────────────────────────────────────────────

    public function test_labelled_fields_are_read_and_prose_is_not(): void
    {
        $parsed = app(CandidateService::class)->parseResumeText(implode("\n", self::FULL_CV));

        $this->assertSame('Acme Technologies Pvt Ltd', $parsed['current_company']);
        $this->assertSame('Senior Software Engineer', $parsed['current_designation']);
        $this->assertSame('Platform Engineering', $parsed['current_department']);
        $this->assertSame('Priya Nair', $parsed['referred_by_name']);
    }

    public function test_the_word_department_in_a_sentence_is_not_a_department(): void
    {
        $parsed = app(CandidateService::class)->parseResumeText(
            "John Doe\nI worked closely with the department to deliver the project.\n"
        );

        $this->assertNull($parsed['current_department']);
    }

    public function test_a_run_on_line_is_rejected_rather_than_stored(): void
    {
        $parsed = app(CandidateService::class)->parseResumeText(
            "Department: I have worked across finance, operations, logistics and human resources over twelve years.\n"
        );

        // A field value is a phrase. A sentence that begins with the label is a
        // paragraph, and storing it would put junk on the candidate's record.
        $this->assertNull($parsed['current_department']);
    }

    public function test_references_available_on_request_yields_no_references(): void
    {
        $parsed = app(CandidateService::class)->parseResumeText(
            "Vikram Singh\n\nReferences\nAvailable on request\n"
        );

        $this->assertSame([], $parsed['professional_references']);
    }

    public function test_reference_lines_need_a_contact_detail(): void
    {
        $parsed = app(CandidateService::class)->parseResumeText(
            "References\n"
            ."Sunil Mehta, Director - sunil.mehta@globex.com\n"
            ."Some heading with no contact information\n"
        );

        $this->assertCount(1, $parsed['professional_references']);
        $this->assertStringContainsString('Sunil Mehta', $parsed['professional_references'][0]);
    }

    // ── the fill rule ──────────────────────────────────────────────────────

    public function test_upload_fills_blank_fields_and_reports_them(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $response = $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        $fresh = $candidate->fresh();
        $this->assertSame('Platform Engineering', $fresh->current_department);
        $this->assertSame('Senior Software Engineer', $fresh->current_designation);
        $this->assertSame('Acme Technologies Pvt Ltd', $fresh->current_company);
        $this->assertSame('Priya Nair', $fresh->referred_by_name);

        $response->assertJsonPath('auto_filled', function (array $filled) {
            return in_array('current_department', $filled, true)
                && in_array('referred_by_name', $filled, true);
        });
    }

    public function test_a_value_already_present_is_never_overwritten(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate([
            'current_department'  => 'Finance',            // typed by the recruiter
            'current_designation' => 'Finance Controller',
        ]);

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        $fresh = $candidate->fresh();

        // What a human entered outranks what a regex found.
        $this->assertSame('Finance', $fresh->current_department);
        $this->assertSame('Finance Controller', $fresh->current_designation);

        // The blanks are still filled — "don't overwrite" is not "don't run".
        $this->assertSame('Acme Technologies Pvt Ltd', $fresh->current_company);
    }

    public function test_a_referrer_matching_one_employee_is_linked(): void
    {
        Sanctum::actingAs($this->actor);
        $referrer  = $this->employee('Priya Nair');
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        $fresh = $candidate->fresh();
        $this->assertSame($referrer->id, $fresh->referred_by_id);
        $this->assertSame('Employee Referral', $fresh->source);
    }

    public function test_an_ambiguous_referrer_stays_an_unlinked_name(): void
    {
        Sanctum::actingAs($this->actor);
        $this->employee('Priya Nair');
        $this->employee('Priya Nair');   // two people, same name
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        $fresh = $candidate->fresh();

        // Referral bonuses are paid on this link, so guessing between two people
        // is worse than leaving it as a name.
        $this->assertNull($fresh->referred_by_id);
        $this->assertSame('Priya Nair', $fresh->referred_by_name);
    }

    public function test_a_referrer_from_another_tenant_is_not_linked(): void
    {
        (new Tenant())->forceFill([
            'id' => 2, 'name' => 'T2', 'slug' => 't2', 'subdomain' => 't2', 'status' => 'active',
        ])->save();

        HrEmployee::create([
            'tenant_id' => 2, 'name' => 'Priya Nair', 'employee_code' => 'E999',
            'department' => 'Engineering', 'designation' => 'Engineer',
            'joining_date' => '2020-01-01', 'status' => 'Active',
        ]);

        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        $this->assertNull($candidate->fresh()->referred_by_id);
    }

    // ── the re-extract endpoint ────────────────────────────────────────────

    public function test_extract_reruns_on_a_resume_already_on_disk(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        // Simulate a record from before auto-fetch existed: the file is stored,
        // the fields are empty.
        $candidate->forceFill([
            'current_department' => null, 'current_designation' => null,
            'current_company' => null, 'referred_by_name' => null, 'referred_by_id' => null,
        ])->save();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume/extract")
            ->assertOk()
            ->assertJsonPath('success', true)
            ->assertJsonPath('candidate.current_department', 'Platform Engineering');
    }

    public function test_extract_on_a_second_run_reports_nothing_new(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume", [
            'resume' => $this->resumePdf(self::FULL_CV),
        ])->assertOk();

        // Upload already filled everything, so a re-run has nothing left to do.
        $this->postJson("/api/hr/candidates/{$candidate->id}/resume/extract")
            ->assertOk()
            ->assertJsonPath('auto_filled', []);
    }

    public function test_extract_without_a_resume_is_a_404(): void
    {
        Sanctum::actingAs($this->actor);
        $candidate = $this->candidate();

        $this->postJson("/api/hr/candidates/{$candidate->id}/resume/extract")->assertStatus(404);
    }

    public function test_extract_is_tenant_scoped(): void
    {
        (new Tenant())->forceFill([
            'id' => 2, 'name' => 'T2', 'slug' => 't2', 'subdomain' => 't2', 'status' => 'active',
        ])->save();

        $foreign = HrCandidate::create([
            'tenant_id' => 2, 'name' => 'Other Tenant', 'email' => 'o'.uniqid().'@test.com', 'stage' => 'Applied',
        ]);

        Sanctum::actingAs($this->actor);

        $this->postJson("/api/hr/candidates/{$foreign->id}/resume/extract")->assertStatus(404);
    }
}
