<?php

namespace Sire\Support;

/**
 * SIRE — the route → context map, server side.
 *
 * GENERATED FILE. Do not edit.
 * Source:    resources/js/lib/sire/contextRoutes.js
 * Generator: tools/generate-route-map.mjs
 * Guarded by tests/route-map-sync.test.mjs, which fails the build if this file
 * and the JavaScript map disagree.
 *
 * The map is SEEDED from the CRM discovery report, not read from the CRM's route
 * registry. Reconcile it with `node tools/sire-route-audit.mjs <routes-file>`,
 * edit the JAVASCRIPT map, and re-run the generator.
 *
 * 359 routes, 27 modules.
 */
final class SireRouteMap
{
    /** @var array<int, array<string, string>> */
    public const ROUTES = [
        ['pattern' => '/app', 'module' => 'dashboard', 'section' => 'home', 'screen' => 'dashboard'],
        ['pattern' => '/app/dashboard', 'module' => 'dashboard', 'section' => 'home', 'screen' => 'dashboard'],
        ['pattern' => '/app/sales', 'module' => 'sales', 'section' => 'overview', 'screen' => 'sales-overview'],
        ['pattern' => '/app/sales/leads', 'module' => 'sales', 'section' => 'leads', 'screen' => 'lead-list'],
        ['pattern' => '/app/sales/leads/:id', 'module' => 'sales', 'section' => 'leads', 'screen' => 'lead-details', 'entity_type' => 'lead'],
        ['pattern' => '/app/sales/leads/:id/edit', 'module' => 'sales', 'section' => 'leads', 'screen' => 'lead-edit', 'entity_type' => 'lead'],
        ['pattern' => '/app/sales/deals', 'module' => 'sales', 'section' => 'deals', 'screen' => 'deal-list'],
        ['pattern' => '/app/sales/deals/:id', 'module' => 'sales', 'section' => 'deals', 'screen' => 'deal-details', 'entity_type' => 'deal'],
        ['pattern' => '/app/sales/quotes', 'module' => 'sales', 'section' => 'quotes', 'screen' => 'quote-list'],
        ['pattern' => '/app/sales/quotes/:id', 'module' => 'sales', 'section' => 'quotes', 'screen' => 'quote-details', 'entity_type' => 'quote'],
        ['pattern' => '/app/sales/proposals', 'module' => 'sales', 'section' => 'proposals', 'screen' => 'proposal-list'],
        ['pattern' => '/app/sales/proposals/:id', 'module' => 'sales', 'section' => 'proposals', 'screen' => 'proposal-details', 'entity_type' => 'proposal'],
        ['pattern' => '/app/sales/invoices', 'module' => 'sales', 'section' => 'invoices', 'screen' => 'invoice-list'],
        ['pattern' => '/app/sales/invoices/:id', 'module' => 'sales', 'section' => 'invoices', 'screen' => 'invoice-details', 'entity_type' => 'invoice'],
        ['pattern' => '/app/sales/commissions', 'module' => 'sales', 'section' => 'commissions', 'screen' => 'commission-list'],
        ['pattern' => '/app/customer/clients', 'module' => 'customer', 'section' => 'clients', 'screen' => 'client-list'],
        ['pattern' => '/app/customer/clients/:id', 'module' => 'customer', 'section' => 'clients', 'screen' => 'client-details', 'entity_type' => 'client'],
        ['pattern' => '/app/customer/clients/:id/timeline', 'module' => 'customer', 'section' => 'clients', 'screen' => 'client-timeline', 'entity_type' => 'client'],
        ['pattern' => '/app/customer/contracts', 'module' => 'customer', 'section' => 'contracts', 'screen' => 'contract-list'],
        ['pattern' => '/app/customer/contracts/:id', 'module' => 'customer', 'section' => 'contracts', 'screen' => 'contract-details', 'entity_type' => 'contract'],
        ['pattern' => '/app/customer/complaints', 'module' => 'customer', 'section' => 'complaints', 'screen' => 'complaint-list'],
        ['pattern' => '/app/helpdesk/tickets', 'module' => 'helpdesk', 'section' => 'tickets', 'screen' => 'ticket-list'],
        ['pattern' => '/app/helpdesk/tickets/:id', 'module' => 'helpdesk', 'section' => 'tickets', 'screen' => 'ticket-details', 'entity_type' => 'ticket'],
        ['pattern' => '/app/helpdesk/kb', 'module' => 'helpdesk', 'section' => 'knowledge-base', 'screen' => 'kb-list'],
        ['pattern' => '/app/helpdesk/kb/:id', 'module' => 'helpdesk', 'section' => 'knowledge-base', 'screen' => 'kb-article', 'entity_type' => 'kb_article'],
        ['pattern' => '/app/tasks', 'module' => 'tasks', 'section' => 'tasks', 'screen' => 'task-list'],
        ['pattern' => '/app/tasks/:id', 'module' => 'tasks', 'section' => 'tasks', 'screen' => 'task-details', 'entity_type' => 'task'],
        ['pattern' => '/app/projects', 'module' => 'projects', 'section' => 'projects', 'screen' => 'project-list'],
        ['pattern' => '/app/projects/:id', 'module' => 'projects', 'section' => 'projects', 'screen' => 'project-details', 'entity_type' => 'project'],
        ['pattern' => '/app/projects/:projectId/milestones', 'module' => 'projects', 'section' => 'milestones', 'screen' => 'milestone-list', 'entity_type' => 'project', 'entity_param' => 'projectId'],
        ['pattern' => '/app/projects/:projectId/tasks/:id', 'module' => 'projects', 'section' => 'project-tasks', 'screen' => 'project-task-details', 'entity_type' => 'task'],
        ['pattern' => '/app/hr/candidates', 'module' => 'hr', 'section' => 'recruitment', 'screen' => 'candidate-list'],
        ['pattern' => '/app/hr/candidates/:id', 'module' => 'hr', 'section' => 'recruitment', 'screen' => 'candidate-details', 'entity_type' => 'candidate'],
        ['pattern' => '/app/hr/employees', 'module' => 'hr', 'section' => 'employees', 'screen' => 'employee-list'],
        ['pattern' => '/app/hr/employees/:id', 'module' => 'hr', 'section' => 'employees', 'screen' => 'employee-details', 'entity_type' => 'employee'],
        ['pattern' => '/app/hr/leave', 'module' => 'hr', 'section' => 'leave', 'screen' => 'leave-list'],
        ['pattern' => '/app/hr/attendance', 'module' => 'hr', 'section' => 'attendance', 'screen' => 'attendance-list'],
        ['pattern' => '/app/hr/onboarding/:id', 'module' => 'hr', 'section' => 'onboarding', 'screen' => 'onboarding-details', 'entity_type' => 'onboarding'],
        ['pattern' => '/app/accounts/vouchers', 'module' => 'accounts', 'section' => 'vouchers', 'screen' => 'voucher-list'],
        ['pattern' => '/app/accounts/vouchers/:id', 'module' => 'accounts', 'section' => 'vouchers', 'screen' => 'voucher-details', 'entity_type' => 'voucher'],
        ['pattern' => '/app/accounts/ledgers', 'module' => 'accounts', 'section' => 'ledgers', 'screen' => 'ledger-list'],
        ['pattern' => '/app/accounts/ledgers/:id', 'module' => 'accounts', 'section' => 'ledgers', 'screen' => 'ledger-details', 'entity_type' => 'ledger'],
        ['pattern' => '/app/accounts/reconciliation', 'module' => 'accounts', 'section' => 'banking', 'screen' => 'reconciliation'],
        ['pattern' => '/app/inventory/products', 'module' => 'inventory', 'section' => 'products', 'screen' => 'product-list'],
        ['pattern' => '/app/inventory/products/:id', 'module' => 'inventory', 'section' => 'products', 'screen' => 'product-details', 'entity_type' => 'product'],
        ['pattern' => '/app/inventory/movements', 'module' => 'inventory', 'section' => 'movements', 'screen' => 'movement-list'],
        ['pattern' => '/app/inventory/cycle-counts', 'module' => 'inventory', 'section' => 'cycle-counts', 'screen' => 'cycle-count-list'],
        ['pattern' => '/app/purchase/requisitions', 'module' => 'purchase', 'section' => 'requisitions', 'screen' => 'pr-list'],
        ['pattern' => '/app/purchase/requisitions/:id', 'module' => 'purchase', 'section' => 'requisitions', 'screen' => 'pr-details', 'entity_type' => 'purchase_requisition'],
        ['pattern' => '/app/purchase/rfqs', 'module' => 'purchase', 'section' => 'rfqs', 'screen' => 'rfq-list'],
        ['pattern' => '/app/purchase/orders', 'module' => 'purchase', 'section' => 'orders', 'screen' => 'po-list'],
        ['pattern' => '/app/purchase/orders/:id', 'module' => 'purchase', 'section' => 'orders', 'screen' => 'po-details', 'entity_type' => 'purchase_order'],
        ['pattern' => '/app/purchase/grn', 'module' => 'purchase', 'section' => 'grn', 'screen' => 'grn-list'],
        ['pattern' => '/app/purchase/vendors/:id', 'module' => 'purchase', 'section' => 'vendors', 'screen' => 'vendor-details', 'entity_type' => 'purchase_vendor'],
        ['pattern' => '/app/tpv/vendors', 'module' => 'tpv', 'section' => 'vendors', 'screen' => 'vendor-list'],
        ['pattern' => '/app/tpv/vendors/:id', 'module' => 'tpv', 'section' => 'vendors', 'screen' => 'vendor-details', 'entity_type' => 'tpv_vendor'],
        ['pattern' => '/app/tpv/workers', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'worker-list'],
        ['pattern' => '/app/tpv/permits', 'module' => 'tpv', 'section' => 'permits', 'screen' => 'permit-list'],
        ['pattern' => '/app/tpv/incidents', 'module' => 'tpv', 'section' => 'hsse', 'screen' => 'incident-list'],
        ['pattern' => '/app/tpv/incidents/:id', 'module' => 'tpv', 'section' => 'hsse', 'screen' => 'incident-details', 'entity_type' => 'hsse_incident'],
        ['pattern' => '/app/compliance/checklists', 'module' => 'compliance', 'section' => 'checklists', 'screen' => 'checklist-list'],
        ['pattern' => '/app/compliance/checklists/:id', 'module' => 'compliance', 'section' => 'checklists', 'screen' => 'checklist-details', 'entity_type' => 'compliance_checklist'],
        ['pattern' => '/app/shared/meetings', 'module' => 'shared', 'section' => 'meetings', 'screen' => 'meeting-list'],
        ['pattern' => '/app/shared/meetings/:id', 'module' => 'shared', 'section' => 'meetings', 'screen' => 'meeting-details', 'entity_type' => 'kickoff_meeting'],
        ['pattern' => '/app/notifications', 'module' => 'notifications', 'section' => 'inbox', 'screen' => 'notification-list'],
        ['pattern' => '/app/settings/*', 'module' => 'settings', 'section' => 'settings', 'screen' => 'settings'],
        ['pattern' => '/app/sire', 'module' => 'sire', 'section' => 'register', 'screen' => 'register-list'],
        ['pattern' => '/app/sire/cases/:id', 'module' => 'sire', 'section' => 'register', 'screen' => 'case-details', 'entity_type' => 'sire_report'],
        ['pattern' => '/app/sire/actions', 'module' => 'sire', 'section' => 'actions', 'screen' => 'actions-queue'],
        ['pattern' => '/app/sire/approvals', 'module' => 'sire', 'section' => 'approvals', 'screen' => 'approvals-queue'],
        ['pattern' => '/app/accounts', 'module' => 'accounts', 'section' => 'accounts', 'screen' => 'accounts-list'],
        ['pattern' => '/app/accounts/banking', 'module' => 'accounts', 'section' => 'banking', 'screen' => 'banking'],
        ['pattern' => '/app/accounts/banking/:bankId/reconcile', 'module' => 'accounts', 'section' => 'banking', 'screen' => 'banking-reconcile'],
        ['pattern' => '/app/accounts/bills', 'module' => 'accounts', 'section' => 'bills', 'screen' => 'bills'],
        ['pattern' => '/app/accounts/budgets', 'module' => 'accounts', 'section' => 'budgets', 'screen' => 'budgets'],
        ['pattern' => '/app/accounts/budgets/:id', 'module' => 'accounts', 'section' => 'budgets', 'screen' => 'budgets-details', 'entity_type' => 'budget'],
        ['pattern' => '/app/accounts/chart-of-accounts', 'module' => 'accounts', 'section' => 'chart-of-accounts', 'screen' => 'chart-of-accounts'],
        ['pattern' => '/app/accounts/cheques', 'module' => 'accounts', 'section' => 'cheques', 'screen' => 'cheques'],
        ['pattern' => '/app/accounts/dashboard', 'module' => 'accounts', 'section' => 'dashboard', 'screen' => 'dashboard'],
        ['pattern' => '/app/accounts/registers', 'module' => 'accounts', 'section' => 'registers', 'screen' => 'registers'],
        ['pattern' => '/app/accounts/registers/:ledgerId', 'module' => 'accounts', 'section' => 'registers', 'screen' => 'registers-details', 'entity_type' => 'register', 'entity_param' => 'ledgerId'],
        ['pattern' => '/app/accounts/reports', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports'],
        ['pattern' => '/app/accounts/reports/ageing', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-ageing'],
        ['pattern' => '/app/accounts/reports/balance-sheet', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-balance-sheet'],
        ['pattern' => '/app/accounts/reports/cash-flow', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-cash-flow'],
        ['pattern' => '/app/accounts/reports/day-book', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-day-book'],
        ['pattern' => '/app/accounts/reports/general-ledger', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-general-ledger'],
        ['pattern' => '/app/accounts/reports/gstr-1', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-gstr-1'],
        ['pattern' => '/app/accounts/reports/gstr-3b', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-gstr-3b'],
        ['pattern' => '/app/accounts/reports/ledger-statement', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-ledger-statement'],
        ['pattern' => '/app/accounts/reports/profit-loss', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-profit-loss'],
        ['pattern' => '/app/accounts/reports/tds', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-tds'],
        ['pattern' => '/app/accounts/reports/trial-balance', 'module' => 'accounts', 'section' => 'reports', 'screen' => 'reports-trial-balance'],
        ['pattern' => '/app/accounts/settings', 'module' => 'accounts', 'section' => 'settings', 'screen' => 'settings'],
        ['pattern' => '/app/accounts/transfer', 'module' => 'accounts', 'section' => 'transfer', 'screen' => 'transfer'],
        ['pattern' => '/app/admin', 'module' => 'admin', 'section' => 'admin', 'screen' => 'admin-list'],
        ['pattern' => '/app/admin/staff', 'module' => 'admin', 'section' => 'staff', 'screen' => 'staff'],
        ['pattern' => '/app/contacts', 'module' => 'contacts', 'section' => 'contacts', 'screen' => 'contacts-list'],
        ['pattern' => '/app/contacts/:id', 'module' => 'contacts', 'section' => 'contacts', 'screen' => 'contacts-details', 'entity_type' => 'contact'],
        ['pattern' => '/app/contacts/new', 'module' => 'contacts', 'section' => 'new', 'screen' => 'new'],
        ['pattern' => '/app/contracts', 'module' => 'contracts', 'section' => 'contracts', 'screen' => 'contracts-list'],
        ['pattern' => '/app/contracts/:id', 'module' => 'contracts', 'section' => 'contracts', 'screen' => 'contracts-details', 'entity_type' => 'contract'],
        ['pattern' => '/app/contracts/:id/edit', 'module' => 'contracts', 'section' => 'edit', 'screen' => 'edit'],
        ['pattern' => '/app/contracts/new', 'module' => 'contracts', 'section' => 'new', 'screen' => 'new'],
        ['pattern' => '/app/customers', 'module' => 'customers', 'section' => 'customers', 'screen' => 'customers-list'],
        ['pattern' => '/app/customers/:id', 'module' => 'customers', 'section' => 'customers', 'screen' => 'customers-details', 'entity_type' => 'customer'],
        ['pattern' => '/app/customers/group-reports', 'module' => 'customers', 'section' => 'group-reports', 'screen' => 'group-reports'],
        ['pattern' => '/app/deals', 'module' => 'deals', 'section' => 'deals', 'screen' => 'deals-list'],
        ['pattern' => '/app/deals/:id', 'module' => 'deals', 'section' => 'deals', 'screen' => 'deals-details', 'entity_type' => 'deal'],
        ['pattern' => '/app/deals/new', 'module' => 'deals', 'section' => 'new', 'screen' => 'new'],
        ['pattern' => '/app/helpdesk', 'module' => 'helpdesk', 'section' => 'helpdesk', 'screen' => 'helpdesk-list'],
        ['pattern' => '/app/helpdesk/analytics', 'module' => 'helpdesk', 'section' => 'analytics', 'screen' => 'analytics'],
        ['pattern' => '/app/helpdesk/kb-admin', 'module' => 'helpdesk', 'section' => 'kb-admin', 'screen' => 'kb-admin'],
        ['pattern' => '/app/helpdesk/knowledge-base', 'module' => 'helpdesk', 'section' => 'knowledge-base', 'screen' => 'knowledge-base'],
        ['pattern' => '/app/helpdesk/knowledge-base/:id', 'module' => 'helpdesk', 'section' => 'knowledge-base', 'screen' => 'knowledge-base-details', 'entity_type' => 'knowledge_base'],
        ['pattern' => '/app/helpdesk/reports', 'module' => 'helpdesk', 'section' => 'reports', 'screen' => 'reports'],
        ['pattern' => '/app/helpdesk/settings', 'module' => 'helpdesk', 'section' => 'settings', 'screen' => 'settings'],
        ['pattern' => '/app/helpdesk/widget', 'module' => 'helpdesk', 'section' => 'widget', 'screen' => 'widget'],
        ['pattern' => '/app/hr', 'module' => 'hr', 'section' => 'hr', 'screen' => 'hr-list'],
        ['pattern' => '/app/hr/advances', 'module' => 'hr', 'section' => 'advances', 'screen' => 'advances'],
        ['pattern' => '/app/hr/attendance-reports', 'module' => 'hr', 'section' => 'attendance-reports', 'screen' => 'attendance-reports'],
        ['pattern' => '/app/hr/company-approvals', 'module' => 'hr', 'section' => 'company-approvals', 'screen' => 'company-approvals'],
        ['pattern' => '/app/hr/corrections', 'module' => 'hr', 'section' => 'corrections', 'screen' => 'corrections'],
        ['pattern' => '/app/hr/dashboard', 'module' => 'hr', 'section' => 'dashboard', 'screen' => 'dashboard'],
        ['pattern' => '/app/hr/demo-requests', 'module' => 'hr', 'section' => 'demo-requests', 'screen' => 'demo-requests'],
        ['pattern' => '/app/hr/employee-onboarding', 'module' => 'hr', 'section' => 'employee-onboarding', 'screen' => 'employee-onboarding'],
        ['pattern' => '/app/hr/employee-onboarding/:id', 'module' => 'hr', 'section' => 'employee-onboarding', 'screen' => 'employee-onboarding-details', 'entity_type' => 'employee_onboarding'],
        ['pattern' => '/app/hr/employees/:id/exit-interview', 'module' => 'hr', 'section' => 'employees', 'screen' => 'employees-exit-interview'],
        ['pattern' => '/app/hr/exit-management', 'module' => 'hr', 'section' => 'exit-management', 'screen' => 'exit-management'],
        ['pattern' => '/app/hr/expense-claims', 'module' => 'hr', 'section' => 'expense-claims', 'screen' => 'expense-claims'],
        ['pattern' => '/app/hr/holidays', 'module' => 'hr', 'section' => 'holidays', 'screen' => 'holidays'],
        ['pattern' => '/app/hr/interview-questions', 'module' => 'hr', 'section' => 'interview-questions', 'screen' => 'interview-questions'],
        ['pattern' => '/app/hr/interviews', 'module' => 'hr', 'section' => 'interviews', 'screen' => 'interviews'],
        ['pattern' => '/app/hr/interviews/:id', 'module' => 'hr', 'section' => 'interviews', 'screen' => 'interviews-details', 'entity_type' => 'interview'],
        ['pattern' => '/app/hr/jobs', 'module' => 'hr', 'section' => 'jobs', 'screen' => 'jobs'],
        ['pattern' => '/app/hr/jobs/:id', 'module' => 'hr', 'section' => 'jobs', 'screen' => 'jobs-details', 'entity_type' => 'job'],
        ['pattern' => '/app/hr/learning-development', 'module' => 'hr', 'section' => 'learning-development', 'screen' => 'learning-development'],
        ['pattern' => '/app/hr/leave-management', 'module' => 'hr', 'section' => 'leave-management', 'screen' => 'leave-management'],
        ['pattern' => '/app/hr/manpower-requests', 'module' => 'hr', 'section' => 'manpower-requests', 'screen' => 'manpower-requests'],
        ['pattern' => '/app/hr/my-advances', 'module' => 'hr', 'section' => 'my-advances', 'screen' => 'my-advances'],
        ['pattern' => '/app/hr/my-corrections', 'module' => 'hr', 'section' => 'my-corrections', 'screen' => 'my-corrections'],
        ['pattern' => '/app/hr/my-expenses', 'module' => 'hr', 'section' => 'my-expenses', 'screen' => 'my-expenses'],
        ['pattern' => '/app/hr/my-leave', 'module' => 'hr', 'section' => 'my-leave', 'screen' => 'my-leave'],
        ['pattern' => '/app/hr/offers', 'module' => 'hr', 'section' => 'offers', 'screen' => 'offers'],
        ['pattern' => '/app/hr/onboarding', 'module' => 'hr', 'section' => 'onboarding', 'screen' => 'onboarding'],
        ['pattern' => '/app/hr/operations', 'module' => 'hr', 'section' => 'operations', 'screen' => 'operations'],
        ['pattern' => '/app/hr/org-chart', 'module' => 'hr', 'section' => 'org-chart', 'screen' => 'org-chart'],
        ['pattern' => '/app/hr/organization-setup', 'module' => 'hr', 'section' => 'organization-setup', 'screen' => 'organization-setup'],
        ['pattern' => '/app/hr/payroll', 'module' => 'hr', 'section' => 'payroll', 'screen' => 'payroll'],
        ['pattern' => '/app/hr/performance', 'module' => 'hr', 'section' => 'performance', 'screen' => 'performance'],
        ['pattern' => '/app/hr/probation-management', 'module' => 'hr', 'section' => 'probation-management', 'screen' => 'probation-management'],
        ['pattern' => '/app/hr/recruiter-workspace', 'module' => 'hr', 'section' => 'recruiter-workspace', 'screen' => 'recruiter-workspace'],
        ['pattern' => '/app/hr/recruitment-services', 'module' => 'hr', 'section' => 'recruitment-services', 'screen' => 'recruitment-services'],
        ['pattern' => '/app/hr/settings', 'module' => 'hr', 'section' => 'settings', 'screen' => 'settings'],
        ['pattern' => '/app/hr/settings/notifications', 'module' => 'hr', 'section' => 'settings', 'screen' => 'settings-notifications'],
        ['pattern' => '/app/hr/surveys', 'module' => 'hr', 'section' => 'surveys', 'screen' => 'surveys'],
        ['pattern' => '/app/inventory', 'module' => 'inventory', 'section' => 'inventory', 'screen' => 'inventory-list'],
        ['pattern' => '/app/inventory/analytics', 'module' => 'inventory', 'section' => 'analytics', 'screen' => 'analytics'],
        ['pattern' => '/app/inventory/assets', 'module' => 'inventory', 'section' => 'assets', 'screen' => 'assets'],
        ['pattern' => '/app/inventory/counts', 'module' => 'inventory', 'section' => 'counts', 'screen' => 'counts'],
        ['pattern' => '/app/inventory/dead-stock', 'module' => 'inventory', 'section' => 'dead-stock', 'screen' => 'dead-stock'],
        ['pattern' => '/app/inventory/fulfilment', 'module' => 'inventory', 'section' => 'fulfilment', 'screen' => 'fulfilment'],
        ['pattern' => '/app/inventory/history', 'module' => 'inventory', 'section' => 'history', 'screen' => 'history'],
        ['pattern' => '/app/inventory/manufacturing', 'module' => 'inventory', 'section' => 'manufacturing', 'screen' => 'manufacturing'],
        ['pattern' => '/app/inventory/purchase-orders', 'module' => 'inventory', 'section' => 'purchase-orders', 'screen' => 'purchase-orders'],
        ['pattern' => '/app/inventory/rentals', 'module' => 'inventory', 'section' => 'rentals', 'screen' => 'rentals'],
        ['pattern' => '/app/inventory/reports', 'module' => 'inventory', 'section' => 'reports', 'screen' => 'reports'],
        ['pattern' => '/app/inventory/scan', 'module' => 'inventory', 'section' => 'scan', 'screen' => 'scan'],
        ['pattern' => '/app/inventory/settings', 'module' => 'inventory', 'section' => 'settings', 'screen' => 'settings'],
        ['pattern' => '/app/inventory/traceability', 'module' => 'inventory', 'section' => 'traceability', 'screen' => 'traceability'],
        ['pattern' => '/app/inventory/transfers', 'module' => 'inventory', 'section' => 'transfers', 'screen' => 'transfers'],
        ['pattern' => '/app/inventory/vendors', 'module' => 'inventory', 'section' => 'vendors', 'screen' => 'vendors'],
        ['pattern' => '/app/inventory/vmi', 'module' => 'inventory', 'section' => 'vmi', 'screen' => 'vmi'],
        ['pattern' => '/app/inventory/vouchers/:type', 'module' => 'inventory', 'section' => 'vouchers', 'screen' => 'vouchers-details', 'entity_type' => 'voucher', 'entity_param' => 'type'],
        ['pattern' => '/app/inventory/warehouses', 'module' => 'inventory', 'section' => 'warehouses', 'screen' => 'warehouses'],
        ['pattern' => '/app/medical/general', 'module' => 'medical', 'section' => 'general', 'screen' => 'general'],
        ['pattern' => '/app/medical/general/report', 'module' => 'medical', 'section' => 'general', 'screen' => 'general-report'],
        ['pattern' => '/app/meetings', 'module' => 'meetings', 'section' => 'meetings', 'screen' => 'meetings-list'],
        ['pattern' => '/app/meetings/:id', 'module' => 'meetings', 'section' => 'meetings', 'screen' => 'meetings-details', 'entity_type' => 'meeting'],
        ['pattern' => '/app/meetings/:id/edit', 'module' => 'meetings', 'section' => 'edit', 'screen' => 'edit'],
        ['pattern' => '/app/meetings/new', 'module' => 'meetings', 'section' => 'new', 'screen' => 'new'],
        ['pattern' => '/app/modules', 'module' => 'modules', 'section' => 'modules', 'screen' => 'modules-list'],
        ['pattern' => '/app/profile', 'module' => 'profile', 'section' => 'profile', 'screen' => 'profile-list'],
        ['pattern' => '/app/purchase', 'module' => 'purchase', 'section' => 'purchase', 'screen' => 'purchase-list'],
        ['pattern' => '/app/purchase/analytics', 'module' => 'purchase', 'section' => 'analytics', 'screen' => 'analytics'],
        ['pattern' => '/app/purchase/approval-requests', 'module' => 'purchase', 'section' => 'approval-requests', 'screen' => 'approval-requests'],
        ['pattern' => '/app/purchase/attendance', 'module' => 'purchase', 'section' => 'attendance', 'screen' => 'attendance'],
        ['pattern' => '/app/purchase/authority-matrix', 'module' => 'purchase', 'section' => 'authority-matrix', 'screen' => 'authority-matrix'],
        ['pattern' => '/app/purchase/capa', 'module' => 'purchase', 'section' => 'capa', 'screen' => 'capa'],
        ['pattern' => '/app/purchase/catalog', 'module' => 'purchase', 'section' => 'catalog', 'screen' => 'catalog'],
        ['pattern' => '/app/purchase/communications', 'module' => 'purchase', 'section' => 'communications', 'screen' => 'communications'],
        ['pattern' => '/app/purchase/competency', 'module' => 'purchase', 'section' => 'competency', 'screen' => 'competency'],
        ['pattern' => '/app/purchase/compliance-register', 'module' => 'purchase', 'section' => 'compliance-register', 'screen' => 'compliance-register'],
        ['pattern' => '/app/purchase/contracts', 'module' => 'purchase', 'section' => 'contracts', 'screen' => 'contracts'],
        ['pattern' => '/app/purchase/contracts/:id', 'module' => 'purchase', 'section' => 'contracts', 'screen' => 'contracts-details', 'entity_type' => 'contract'],
        ['pattern' => '/app/purchase/dashboard', 'module' => 'purchase', 'section' => 'dashboard', 'screen' => 'dashboard'],
        ['pattern' => '/app/purchase/debit-notes', 'module' => 'purchase', 'section' => 'debit-notes', 'screen' => 'debit-notes'],
        ['pattern' => '/app/purchase/document-vault', 'module' => 'purchase', 'section' => 'document-vault', 'screen' => 'document-vault'],
        ['pattern' => '/app/purchase/evidence', 'module' => 'purchase', 'section' => 'evidence', 'screen' => 'evidence'],
        ['pattern' => '/app/purchase/gate-log', 'module' => 'purchase', 'section' => 'gate-log', 'screen' => 'gate-log'],
        ['pattern' => '/app/purchase/goods-received', 'module' => 'purchase', 'section' => 'goods-received', 'screen' => 'goods-received'],
        ['pattern' => '/app/purchase/governance', 'module' => 'purchase', 'section' => 'governance', 'screen' => 'governance'],
        ['pattern' => '/app/purchase/incidents', 'module' => 'purchase', 'section' => 'incidents', 'screen' => 'incidents'],
        ['pattern' => '/app/purchase/inspections', 'module' => 'purchase', 'section' => 'inspections', 'screen' => 'inspections'],
        ['pattern' => '/app/purchase/invoices', 'module' => 'purchase', 'section' => 'invoices', 'screen' => 'invoices'],
        ['pattern' => '/app/purchase/kickoff', 'module' => 'purchase', 'section' => 'kickoff', 'screen' => 'kickoff'],
        ['pattern' => '/app/purchase/kickoff/:id', 'module' => 'purchase', 'section' => 'kickoff', 'screen' => 'kickoff-details', 'entity_type' => 'kickoff'],
        ['pattern' => '/app/purchase/kickoff/:id/edit', 'module' => 'purchase', 'section' => 'kickoff', 'screen' => 'kickoff-edit'],
        ['pattern' => '/app/purchase/kickoff/new', 'module' => 'purchase', 'section' => 'kickoff', 'screen' => 'kickoff-new'],
        ['pattern' => '/app/purchase/medical', 'module' => 'purchase', 'section' => 'medical', 'screen' => 'medical'],
        ['pattern' => '/app/purchase/medical/doctors', 'module' => 'purchase', 'section' => 'medical', 'screen' => 'medical-doctors'],
        ['pattern' => '/app/purchase/medical/report', 'module' => 'purchase', 'section' => 'medical', 'screen' => 'medical-report'],
        ['pattern' => '/app/purchase/meetings/registers', 'module' => 'purchase', 'section' => 'meetings', 'screen' => 'meetings-registers'],
        ['pattern' => '/app/purchase/meetings/registers/:register', 'module' => 'purchase', 'section' => 'meetings', 'screen' => 'meetings-registers-details', 'entity_type' => 'meetings_register', 'entity_param' => 'register'],
        ['pattern' => '/app/purchase/ncr', 'module' => 'purchase', 'section' => 'ncr', 'screen' => 'ncr'],
        ['pattern' => '/app/purchase/offboarding', 'module' => 'purchase', 'section' => 'offboarding', 'screen' => 'offboarding'],
        ['pattern' => '/app/purchase/onboarding', 'module' => 'purchase', 'section' => 'onboarding', 'screen' => 'onboarding'],
        ['pattern' => '/app/purchase/onboarding/:id', 'module' => 'purchase', 'section' => 'onboarding', 'screen' => 'onboarding-details', 'entity_type' => 'onboarding'],
        ['pattern' => '/app/purchase/order-returns', 'module' => 'purchase', 'section' => 'order-returns', 'screen' => 'order-returns'],
        ['pattern' => '/app/purchase/permits', 'module' => 'purchase', 'section' => 'permits', 'screen' => 'permits'],
        ['pattern' => '/app/purchase/ppe/matrix', 'module' => 'purchase', 'section' => 'ppe', 'screen' => 'ppe-matrix'],
        ['pattern' => '/app/purchase/prequalification', 'module' => 'purchase', 'section' => 'prequalification', 'screen' => 'prequalification'],
        ['pattern' => '/app/purchase/quotations', 'module' => 'purchase', 'section' => 'quotations', 'screen' => 'quotations'],
        ['pattern' => '/app/purchase/quotations/:id', 'module' => 'purchase', 'section' => 'quotations', 'screen' => 'quotations-details', 'entity_type' => 'quotation'],
        ['pattern' => '/app/purchase/renewals', 'module' => 'purchase', 'section' => 'renewals', 'screen' => 'renewals'],
        ['pattern' => '/app/purchase/reports', 'module' => 'purchase', 'section' => 'reports', 'screen' => 'reports'],
        ['pattern' => '/app/purchase/requests', 'module' => 'purchase', 'section' => 'requests', 'screen' => 'requests'],
        ['pattern' => '/app/purchase/risk', 'module' => 'purchase', 'section' => 'risk', 'screen' => 'risk'],
        ['pattern' => '/app/purchase/safety', 'module' => 'purchase', 'section' => 'safety', 'screen' => 'safety'],
        ['pattern' => '/app/purchase/settings', 'module' => 'purchase', 'section' => 'settings', 'screen' => 'settings'],
        ['pattern' => '/app/purchase/site-registers', 'module' => 'purchase', 'section' => 'site-registers', 'screen' => 'site-registers'],
        ['pattern' => '/app/purchase/vendor-items', 'module' => 'purchase', 'section' => 'vendor-items', 'screen' => 'vendor-items'],
        ['pattern' => '/app/purchase/vendors', 'module' => 'purchase', 'section' => 'vendors', 'screen' => 'vendors'],
        ['pattern' => '/app/purchase/violations', 'module' => 'purchase', 'section' => 'violations', 'screen' => 'violations'],
        ['pattern' => '/app/purchase/vpi', 'module' => 'purchase', 'section' => 'vpi', 'screen' => 'vpi'],
        ['pattern' => '/app/purchase/work-authorization', 'module' => 'purchase', 'section' => 'work-authorization', 'screen' => 'work-authorization'],
        ['pattern' => '/app/purchase/work-packages', 'module' => 'purchase', 'section' => 'work-packages', 'screen' => 'work-packages'],
        ['pattern' => '/app/purchase/workers', 'module' => 'purchase', 'section' => 'workers', 'screen' => 'workers'],
        ['pattern' => '/app/purchase/workers/:id', 'module' => 'purchase', 'section' => 'workers', 'screen' => 'workers-details', 'entity_type' => 'worker'],
        ['pattern' => '/app/purchase/workforce', 'module' => 'purchase', 'section' => 'workforce', 'screen' => 'workforce'],
        ['pattern' => '/app/sales/commission', 'module' => 'sales', 'section' => 'commission', 'screen' => 'commission'],
        ['pattern' => '/app/sales/contracts', 'module' => 'sales', 'section' => 'contracts', 'screen' => 'contracts'],
        ['pattern' => '/app/sales/contracts/:id', 'module' => 'sales', 'section' => 'contracts', 'screen' => 'contracts-details', 'entity_type' => 'contract'],
        ['pattern' => '/app/sales/credit-notes', 'module' => 'sales', 'section' => 'credit-notes', 'screen' => 'credit-notes'],
        ['pattern' => '/app/sales/dashboard', 'module' => 'sales', 'section' => 'dashboard', 'screen' => 'dashboard'],
        ['pattern' => '/app/sales/delivery-notes', 'module' => 'sales', 'section' => 'delivery-notes', 'screen' => 'delivery-notes'],
        ['pattern' => '/app/sales/estimates', 'module' => 'sales', 'section' => 'estimates', 'screen' => 'estimates'],
        ['pattern' => '/app/sales/estimates/:id', 'module' => 'sales', 'section' => 'estimates', 'screen' => 'estimates-details', 'entity_type' => 'estimate'],
        ['pattern' => '/app/sales/estimates/new', 'module' => 'sales', 'section' => 'estimates', 'screen' => 'estimates-new'],
        ['pattern' => '/app/sales/forecast', 'module' => 'sales', 'section' => 'forecast', 'screen' => 'forecast'],
        ['pattern' => '/app/sales/invoices/new', 'module' => 'sales', 'section' => 'invoices', 'screen' => 'invoices-new'],
        ['pattern' => '/app/sales/items', 'module' => 'sales', 'section' => 'items', 'screen' => 'items'],
        ['pattern' => '/app/sales/lead-goals', 'module' => 'sales', 'section' => 'lead-goals', 'screen' => 'lead-goals'],
        ['pattern' => '/app/sales/payment-links', 'module' => 'sales', 'section' => 'payment-links', 'screen' => 'payment-links'],
        ['pattern' => '/app/sales/payments', 'module' => 'sales', 'section' => 'payments', 'screen' => 'payments'],
        ['pattern' => '/app/sales/proforma-invoices', 'module' => 'sales', 'section' => 'proforma-invoices', 'screen' => 'proforma-invoices'],
        ['pattern' => '/app/sales/proposal-templates', 'module' => 'sales', 'section' => 'proposal-templates', 'screen' => 'proposal-templates'],
        ['pattern' => '/app/sales/proposal-templates/:id/edit', 'module' => 'sales', 'section' => 'proposal-templates', 'screen' => 'proposal-templates-edit'],
        ['pattern' => '/app/sales/proposal-templates/new', 'module' => 'sales', 'section' => 'proposal-templates', 'screen' => 'proposal-templates-new'],
        ['pattern' => '/app/sales/proposals/:id/edit', 'module' => 'sales', 'section' => 'proposals', 'screen' => 'proposals-edit'],
        ['pattern' => '/app/sales/proposals/new', 'module' => 'sales', 'section' => 'proposals', 'screen' => 'proposals-new'],
        ['pattern' => '/app/sales/reports', 'module' => 'sales', 'section' => 'reports', 'screen' => 'reports'],
        ['pattern' => '/app/sales/retainer-invoices', 'module' => 'sales', 'section' => 'retainer-invoices', 'screen' => 'retainer-invoices'],
        ['pattern' => '/app/sales/tasks', 'module' => 'sales', 'section' => 'tasks', 'screen' => 'tasks'],
        ['pattern' => '/app/sales/web-to-lead', 'module' => 'sales', 'section' => 'web-to-lead', 'screen' => 'web-to-lead'],
        ['pattern' => '/app/sessions', 'module' => 'sessions', 'section' => 'sessions', 'screen' => 'sessions-list'],
        ['pattern' => '/app/settings/account-groups', 'module' => 'settings', 'section' => 'account-groups', 'screen' => 'account-groups'],
        ['pattern' => '/app/settings/company', 'module' => 'settings', 'section' => 'company', 'screen' => 'company'],
        ['pattern' => '/app/settings/currency', 'module' => 'settings', 'section' => 'currency', 'screen' => 'currency'],
        ['pattern' => '/app/settings/custom-fields', 'module' => 'settings', 'section' => 'custom-fields', 'screen' => 'custom-fields'],
        ['pattern' => '/app/settings/departments', 'module' => 'settings', 'section' => 'departments', 'screen' => 'departments'],
        ['pattern' => '/app/settings/email-templates', 'module' => 'settings', 'section' => 'email-templates', 'screen' => 'email-templates'],
        ['pattern' => '/app/settings/expense-categories', 'module' => 'settings', 'section' => 'expense-categories', 'screen' => 'expense-categories'],
        ['pattern' => '/app/settings/general', 'module' => 'settings', 'section' => 'general', 'screen' => 'general'],
        ['pattern' => '/app/settings/localization', 'module' => 'settings', 'section' => 'localization', 'screen' => 'localization'],
        ['pattern' => '/app/settings/mail', 'module' => 'settings', 'section' => 'mail', 'screen' => 'mail'],
        ['pattern' => '/app/settings/modules/accounts', 'module' => 'settings', 'section' => 'modules', 'screen' => 'modules-accounts'],
        ['pattern' => '/app/settings/modules/helpdesk', 'module' => 'settings', 'section' => 'modules', 'screen' => 'modules-helpdesk'],
        ['pattern' => '/app/settings/modules/purchase', 'module' => 'settings', 'section' => 'modules', 'screen' => 'modules-purchase'],
        ['pattern' => '/app/settings/modules/tpv', 'module' => 'settings', 'section' => 'modules', 'screen' => 'modules-tpv'],
        ['pattern' => '/app/settings/notification-preferences', 'module' => 'settings', 'section' => 'notification-preferences', 'screen' => 'notification-preferences'],
        ['pattern' => '/app/settings/numbering', 'module' => 'settings', 'section' => 'numbering', 'screen' => 'numbering'],
        ['pattern' => '/app/settings/recycle-bin', 'module' => 'settings', 'section' => 'recycle-bin', 'screen' => 'recycle-bin'],
        ['pattern' => '/app/settings/roles', 'module' => 'settings', 'section' => 'roles', 'screen' => 'roles'],
        ['pattern' => '/app/settings/security', 'module' => 'settings', 'section' => 'security', 'screen' => 'security'],
        ['pattern' => '/app/settings/statuses', 'module' => 'settings', 'section' => 'statuses', 'screen' => 'statuses'],
        ['pattern' => '/app/settings/tax-rates', 'module' => 'settings', 'section' => 'tax-rates', 'screen' => 'tax-rates'],
        ['pattern' => '/app/settings/upload', 'module' => 'settings', 'section' => 'upload', 'screen' => 'upload'],
        ['pattern' => '/app/settings/whatsapp', 'module' => 'settings', 'section' => 'whatsapp', 'screen' => 'whatsapp'],
        ['pattern' => '/app/sire/dashboard', 'module' => 'sire', 'section' => 'dashboard', 'screen' => 'dashboard'],
        ['pattern' => '/app/sire/insights', 'module' => 'sire', 'section' => 'insights', 'screen' => 'insights'],
        ['pattern' => '/app/sire/my-work', 'module' => 'sire', 'section' => 'my-work', 'screen' => 'my-work'],
        ['pattern' => '/app/sire/quality', 'module' => 'sire', 'section' => 'quality', 'screen' => 'quality'],
        ['pattern' => '/app/sire/recurring/:id', 'module' => 'sire', 'section' => 'recurring', 'screen' => 'recurring-details', 'entity_type' => 'recurring'],
        ['pattern' => '/app/sire/release-notes/:noteId', 'module' => 'sire', 'section' => 'release-notes', 'screen' => 'release-notes-details', 'entity_type' => 'release_note', 'entity_param' => 'noteId'],
        ['pattern' => '/app/sire/releases', 'module' => 'sire', 'section' => 'releases', 'screen' => 'releases'],
        ['pattern' => '/app/sire/releases/:id', 'module' => 'sire', 'section' => 'releases', 'screen' => 'releases-details', 'entity_type' => 'release'],
        ['pattern' => '/app/tasks/overview', 'module' => 'tasks', 'section' => 'overview', 'screen' => 'overview'],
        ['pattern' => '/app/tickets', 'module' => 'tickets', 'section' => 'tickets', 'screen' => 'tickets-list'],
        ['pattern' => '/app/tpv', 'module' => 'tpv', 'section' => 'tpv', 'screen' => 'tpv-list'],
        ['pattern' => '/app/tpv/analytics', 'module' => 'tpv', 'section' => 'analytics', 'screen' => 'analytics'],
        ['pattern' => '/app/tpv/approval-register', 'module' => 'tpv', 'section' => 'approval-register', 'screen' => 'approval-register'],
        ['pattern' => '/app/tpv/approvals', 'module' => 'tpv', 'section' => 'approvals', 'screen' => 'approvals'],
        ['pattern' => '/app/tpv/authority-matrix', 'module' => 'tpv', 'section' => 'authority-matrix', 'screen' => 'authority-matrix'],
        ['pattern' => '/app/tpv/capa', 'module' => 'tpv', 'section' => 'capa', 'screen' => 'capa'],
        ['pattern' => '/app/tpv/communications', 'module' => 'tpv', 'section' => 'communications', 'screen' => 'communications'],
        ['pattern' => '/app/tpv/competency', 'module' => 'tpv', 'section' => 'competency', 'screen' => 'competency'],
        ['pattern' => '/app/tpv/compliance', 'module' => 'tpv', 'section' => 'compliance', 'screen' => 'compliance'],
        ['pattern' => '/app/tpv/compliance-register', 'module' => 'tpv', 'section' => 'compliance-register', 'screen' => 'compliance-register'],
        ['pattern' => '/app/tpv/compliance/checklists/:id', 'module' => 'tpv', 'section' => 'compliance', 'screen' => 'compliance-checklists-details', 'entity_type' => 'compliance_checklist'],
        ['pattern' => '/app/tpv/compliance/templates/:id', 'module' => 'tpv', 'section' => 'compliance', 'screen' => 'compliance-templates-details', 'entity_type' => 'compliance_template'],
        ['pattern' => '/app/tpv/contracts', 'module' => 'tpv', 'section' => 'contracts', 'screen' => 'contracts'],
        ['pattern' => '/app/tpv/dashboard', 'module' => 'tpv', 'section' => 'dashboard', 'screen' => 'dashboard'],
        ['pattern' => '/app/tpv/document-vault', 'module' => 'tpv', 'section' => 'document-vault', 'screen' => 'document-vault'],
        ['pattern' => '/app/tpv/documents', 'module' => 'tpv', 'section' => 'documents', 'screen' => 'documents'],
        ['pattern' => '/app/tpv/evidence', 'module' => 'tpv', 'section' => 'evidence', 'screen' => 'evidence'],
        ['pattern' => '/app/tpv/gate-log', 'module' => 'tpv', 'section' => 'gate-log', 'screen' => 'gate-log'],
        ['pattern' => '/app/tpv/governance', 'module' => 'tpv', 'section' => 'governance', 'screen' => 'governance'],
        ['pattern' => '/app/tpv/inspections', 'module' => 'tpv', 'section' => 'inspections', 'screen' => 'inspections'],
        ['pattern' => '/app/tpv/kickoff', 'module' => 'tpv', 'section' => 'kickoff', 'screen' => 'kickoff'],
        ['pattern' => '/app/tpv/kickoff/:id', 'module' => 'tpv', 'section' => 'kickoff', 'screen' => 'kickoff-details', 'entity_type' => 'kickoff'],
        ['pattern' => '/app/tpv/kickoff/:id/edit', 'module' => 'tpv', 'section' => 'kickoff', 'screen' => 'kickoff-edit'],
        ['pattern' => '/app/tpv/kickoff/new', 'module' => 'tpv', 'section' => 'kickoff', 'screen' => 'kickoff-new'],
        ['pattern' => '/app/tpv/medical', 'module' => 'tpv', 'section' => 'medical', 'screen' => 'medical'],
        ['pattern' => '/app/tpv/medical/doctors', 'module' => 'tpv', 'section' => 'medical', 'screen' => 'medical-doctors'],
        ['pattern' => '/app/tpv/medical/report', 'module' => 'tpv', 'section' => 'medical', 'screen' => 'medical-report'],
        ['pattern' => '/app/tpv/meetings/registers', 'module' => 'tpv', 'section' => 'meetings', 'screen' => 'meetings-registers'],
        ['pattern' => '/app/tpv/meetings/registers/:register', 'module' => 'tpv', 'section' => 'meetings', 'screen' => 'meetings-registers-details', 'entity_type' => 'meetings_register', 'entity_param' => 'register'],
        ['pattern' => '/app/tpv/ncr', 'module' => 'tpv', 'section' => 'ncr', 'screen' => 'ncr'],
        ['pattern' => '/app/tpv/offboarding', 'module' => 'tpv', 'section' => 'offboarding', 'screen' => 'offboarding'],
        ['pattern' => '/app/tpv/onboarding', 'module' => 'tpv', 'section' => 'onboarding', 'screen' => 'onboarding'],
        ['pattern' => '/app/tpv/onboarding/:id', 'module' => 'tpv', 'section' => 'onboarding', 'screen' => 'onboarding-details', 'entity_type' => 'onboarding'],
        ['pattern' => '/app/tpv/performance', 'module' => 'tpv', 'section' => 'performance', 'screen' => 'performance'],
        ['pattern' => '/app/tpv/ppe', 'module' => 'tpv', 'section' => 'ppe', 'screen' => 'ppe'],
        ['pattern' => '/app/tpv/ppe/matrix', 'module' => 'tpv', 'section' => 'ppe', 'screen' => 'ppe-matrix'],
        ['pattern' => '/app/tpv/prequalification', 'module' => 'tpv', 'section' => 'prequalification', 'screen' => 'prequalification'],
        ['pattern' => '/app/tpv/renewals', 'module' => 'tpv', 'section' => 'renewals', 'screen' => 'renewals'],
        ['pattern' => '/app/tpv/reports', 'module' => 'tpv', 'section' => 'reports', 'screen' => 'reports'],
        ['pattern' => '/app/tpv/risk', 'module' => 'tpv', 'section' => 'risk', 'screen' => 'risk'],
        ['pattern' => '/app/tpv/safety-engagement', 'module' => 'tpv', 'section' => 'safety-engagement', 'screen' => 'safety-engagement'],
        ['pattern' => '/app/tpv/settings', 'module' => 'tpv', 'section' => 'settings', 'screen' => 'settings'],
        ['pattern' => '/app/tpv/site-registers', 'module' => 'tpv', 'section' => 'site-registers', 'screen' => 'site-registers'],
        ['pattern' => '/app/tpv/strikes', 'module' => 'tpv', 'section' => 'strikes', 'screen' => 'strikes'],
        ['pattern' => '/app/tpv/temporary', 'module' => 'tpv', 'section' => 'temporary', 'screen' => 'temporary'],
        ['pattern' => '/app/tpv/view/:id', 'module' => 'tpv', 'section' => 'view', 'screen' => 'view-details', 'entity_type' => 'view'],
        ['pattern' => '/app/tpv/violations', 'module' => 'tpv', 'section' => 'violations', 'screen' => 'violations'],
        ['pattern' => '/app/tpv/vpi', 'module' => 'tpv', 'section' => 'vpi', 'screen' => 'vpi'],
        ['pattern' => '/app/tpv/work-authorization', 'module' => 'tpv', 'section' => 'work-authorization', 'screen' => 'work-authorization'],
        ['pattern' => '/app/tpv/work-packages', 'module' => 'tpv', 'section' => 'work-packages', 'screen' => 'work-packages'],
        ['pattern' => '/app/tpv/workforce', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce'],
        ['pattern' => '/app/tpv/workforce/:id', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-details', 'entity_type' => 'workforce'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-details', 'entity_type' => 'workforce_vendor', 'entity_param' => 'vendorId'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId/attendance', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-attendance'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId/dashboard', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-dashboard'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId/gate-log', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-gate-log'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId/ppe', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-ppe'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId/strikes', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-strikes'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId/workers', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-workers'],
        ['pattern' => '/app/tpv/workforce/vendor/:vendorId/workers/:id', 'module' => 'tpv', 'section' => 'workforce', 'screen' => 'workforce-vendor-workers-details', 'entity_type' => 'workforce_vendor_worker'],
    ];

    /** @var array<string, string> */
    public const MODULE_LABELS = [
        'hr' => 'HR & Recruitment',
        'sales' => 'Sales',
        'customer' => 'Customer 360',
        'accounts' => 'Accounts',
        'helpdesk' => 'Helpdesk',
        'tasks' => 'Tasks',
        'projects' => 'Projects',
        'inventory' => 'Inventory',
        'purchase' => 'Purchase',
        'tpv' => 'TPV / HSSE',
        'compliance' => 'Compliance',
        'shared' => 'Shared',
        'notifications' => 'Notifications',
        'settings' => 'Settings',
        'contracts' => 'Contracts',
        'meetings' => 'Meetings',
        'contacts' => 'Contacts',
        'customers' => 'Customers',
        'deals' => 'Deals',
        'admin' => 'Admin',
        'medical' => 'Medical',
        'dashboard' => 'Dashboard',
        'modules' => 'Modules',
        'profile' => 'Profile',
        'sessions' => 'Sessions',
        'tickets' => 'Tickets',
        'sire' => 'SIRE',
    ];
}
