/**
 * SIRE — engineering workflow, client side.
 *
 * The SERVER is the authority: every transition is validated in
 * App\Services\Sire\SireWorkflowService, and the case detail payload carries
 * `available_transitions` computed there. This module never decides what is
 * legal — it labels, colours and orders what the server already allowed.
 *
 * The definition it reads is generated by `php artisan sire:export-workflow`. Keeping
 * one machine in two languages is a drift risk, so the machine is defined once
 * in PHP and exported; CI fails if the checked-in JSON is stale.
 */
import workflow from './workflow.generated.js';
import { statusToken } from './tokens.js';

export const STATES = workflow.states;
export const TRANSITIONS = workflow.transitions;
export const INITIAL_STATE = workflow.initial;

export const stateLabel = (status) => STATES[status]?.label ?? status ?? '—';
export const stateGroup = (status) => STATES[status]?.group ?? 'intake';
export const isTerminal = (status) => STATES[status]?.terminal === true;
/**
 * Delegates to the shared vocabulary. This module owns the MACHINE; tokens.js
 * owns how a state looks. Keeping a second palette here is how the same status
 * ended up two different reds in two different screens.
 */
export const stateClasses = (status) => statusToken(status, STATES).classes;
export const stateToken = (status) => statusToken(status, STATES);

/** The happy path, for the progress rail. Side states are not on it. */
export const MAIN_PATH = [
  'new', 'triaged', 'assigned', 'in_development',
  'ready_for_qa', 'qa_in_progress', 'qa_passed',
  'ready_for_release', 'released', 'production_validated', 'closed',
];

/**
 * Where to draw the progress rail marker. A side state (qa_failed, on_hold,
 * reopened, and the terminal resolutions) is not on the rail, so the marker
 * rests on the last main-path state the issue actually reached.
 */
export function railPosition(status, lastMainPathStatus = null) {
  const direct = MAIN_PATH.indexOf(status);
  if (direct !== -1) return { index: direct, offRail: false };
  const fallback = MAIN_PATH.indexOf(lastMainPathStatus);
  return { index: fallback === -1 ? 0 : fallback, offRail: true };
}

/** Server-supplied transitions, decorated for display and ordered sensibly. */
export function decorateTransitions(available = []) {
  const byAction = new Map(TRANSITIONS.map((t) => [t.action, t]));
  return available
    .map((item) => {
      const action = typeof item === 'string' ? item : item.action;
      const def = byAction.get(action);
      if (!def) return null; // server knows an action this client build does not
      return {
        action,
        label: (typeof item === 'object' && item.label) || def.label,
        to: def.to,
        tone: STATES[def.to]?.tone ?? 'gray',
        requires: def.requires ?? [],
        destructive: ['reject', 'wont_fix', 'mark_duplicate', 'cannot_reproduce'].includes(action),
        primary: ['start_development', 'mark_ready_for_qa', 'start_qa', 'qa_pass', 'release', 'close'].includes(action),
      };
    })
    .filter(Boolean)
    .sort((a, b) => Number(b.primary) - Number(a.primary) || Number(a.destructive) - Number(b.destructive));
}

/**
 * Pure mirror of the server's legality check. NOT used to gate the UI — it
 * exists so the machine can be reasoned about and tested, and so a mismatch
 * between client and server shows up in tests rather than in production.
 */
export function canTransition(from, action) {
  const def = TRANSITIONS.find((t) => t.action === action);
  return Boolean(def && def.from.includes(from));
}

export function transitionsFrom(from) {
  return TRANSITIONS.filter((t) => t.from.includes(from)).map((t) => t.action);
}

export function resolveTarget(def, report) {
  // '@held_from_status' — resume returns to wherever the hold interrupted.
  if (def.to === '@held_from_status') return report?.held_from_status ?? 'triaged';
  return def.to;
}

export default workflow;
