<?php

namespace App\Http\Controllers\Api\Shared;

use App\Http\Controllers\Controller;
use App\Models\Tenant;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

/**
 * The tenant's default online-meeting platform.
 *
 * A preference, not a credential: it only decides which provider the Kickoff
 * screen preselects. The link is still generated by MeetingProviderFactory,
 * which stays the authority on what each platform can actually do.
 *
 * Stored on tenants.settings (already an array cast) rather than in a table of
 * its own — it is one value per tenant.
 */
class MeetingPlatformController extends Controller
{
    private const KEY = 'default_meeting_platform';

    /** The platforms MeetingProviderFactory can actually build. */
    private const PLATFORMS = ['google_meet', 'zoom', 'teams', 'stub'];

    /* GET /api/settings/meeting-platform */
    public function show(Request $request)
    {
        $tenant = $this->tenant($request);

        return response()->json([
            // Fall back to the configured provider so the UI has a sane default
            // before anyone has chosen one.
            'platform'  => $tenant?->settings[self::KEY] ?? config('meeting.provider', 'stub'),
            'platforms' => self::PLATFORMS,
        ]);
    }

    /* PUT /api/settings/meeting-platform */
    public function update(Request $request)
    {
        abort_unless($request->user()->role === 'admin', 403, 'Only an admin can change this setting.');

        $data = $request->validate([
            'platform' => ['required', Rule::in(self::PLATFORMS)],
        ]);

        $tenant = $this->tenant($request);
        abort_unless($tenant, 404, 'Tenant not found.');

        // Merge, never overwrite — settings holds other tenant preferences too.
        $tenant->settings = array_merge($tenant->settings ?? [], [self::KEY => $data['platform']]);
        $tenant->save();

        return response()->json([
            'platform'  => $data['platform'],
            'platforms' => self::PLATFORMS,
        ]);
    }

    private function tenant(Request $request): ?Tenant
    {
        return Tenant::find($request->user()->tenant_id);
    }
}
