<?php

namespace App\Support\Transport;

/**
 * Transit & Exceptions — SNG-TRN-013's approved scope.
 *
 * ── THE TICKET, AND WHY ITS REGISTRY REFERENCES ARE NOT USED ──────────────
 * Step 12 Ticket_Register:14 reads:
 *
 *   SNG-TRN-013 | Execution | Transit & Exceptions | P0 | S7 | dep SNG-TRN-010
 *   | BE | XL | "Exceptions have severity, owner, SLA and closure evidence."
 *   | FRS-P0-013 | BR-012 | DB-012;API-008;EV-009 | Ready
 *
 * Every one of those four registry references is wrong, and each was checked
 * against the document it names:
 *
 *   FRS-P0-013  FRS TRP-P0-013 is "Delivery / POD capture" — ticket 014's
 *               requirement, not this one.
 *   DB-012      Step 11 DB-012 is not trip_exceptions. DB-010 is.
 *   API-008     Step 11 API-008 is not the exception endpoint. API-007 is.
 *   EV-009      Step 11's event registry uses EVT-nnn. EVT-008 is the row.
 *
 * This is the same fabricated sequential counter recorded against tickets 007
 * and 009 (D-12, D-15): the register's cross-references were generated by
 * position rather than by lookup. Logged as D-35. The REAL anchors are below,
 * and every one of them was read from its own document.
 *
 * ── THE AUTHORITY THIS TICKET ACTUALLY HAS ───────────────────────────────
 * Unlike dispatch (D-18), which had no ticket and no API row, 013 is the
 * best-founded ticket in the module. Step 11 LOCKS all of:
 *
 *   DB-010     trip_exceptions, tenant-scoped on company_id
 *   FLD-014    severity  VARCHAR(20) NOT NULL DEFAULT 'medium'  INDEX
 *   FLD-015    status    VARCHAR(30) NOT NULL DEFAULT 'open'    INDEX
 *   IDX-008    INDEX (company_id, trip_id, severity, status)
 *   API-007    POST /api/v1/transport/trips/{trip}/exceptions
 *   CTR-011    severity: body, ENUM, required, low/medium/high/critical
 *   EVT-008    TripExceptionRaised (exception_id, trip_id, severity)
 *   SM-EXC     open (initial) · acknowledged (active) · resolved (terminal)
 *   STT-015    open → acknowledged
 *   STT-016    acknowledged → resolved
 *   STT-006    dispatched → in_transit
 *   ENUM-003   exception_severity
 *   ENUM-004   exception_status
 *
 * ── THE OWNER'S RULINGS, 2026-09-10 ──────────────────────────────────────
 * Six questions were put and answered before any code was written. Each is
 * recorded below as data, next to the thing it decided.
 *
 * @see AllocationScope  SNG-TRN-009's equivalent ruling.
 * @see PretripScope     SNG-TRN-010's equivalent ruling.
 * @see DispatchScope    Record Dispatch's equivalent ruling.
 */
final class ExceptionScope
{
    public const TICKET = 'SNG-TRN-013';

    /** The owner's rulings, in place of the register's missing detail. */
    public const AUTHORIZATION = 'Owner, 2026-09-10 — Q1..Q6 ruled in writing before build; see RULINGS';

    /**
     * Registry references the ticket gives, and the rows they should have
     * named. Asserted by a test so this cannot quietly rot.
     */
    public const REGISTRY_REF_CORRECTIONS = [
        'FRS-P0-013' => 'FRS TRP-P0-011 (Live trip control) + TRP-P0-012 (Exception management)',
        'BR-012'     => 'BR-P0-010 (Transit) + BR-P0-011 (Exception)',
        'DB-012'     => 'DB-010 trip_exceptions',
        'API-008'    => 'API-007 POST /transport/trips/{trip}/exceptions',
        'EV-009'     => 'EVT-008 TripExceptionRaised',
    ];

    /* ── IN SCOPE — RTM requirements, each read from the RTM ──────────── */

    /** "Track trip status" · LSM · P0 · acceptance "Trip lifecycle controlled". */
    public const OPS_009 = 'STOS-REQ-OPS-009';

    /** "Handle breakdown" · OPS/QC · P0 · acceptance "Breakdown incident workflow". */
    public const OPS_012 = 'STOS-REQ-OPS-012';

    public const IN_SCOPE = [self::OPS_009, self::OPS_012];

    /** The two FRS rows this ticket really implements. */
    public const FRS_TRANSIT   = 'FRS TRP-P0-011 — Transit / Live trip control';
    public const FRS_EXCEPTION = 'FRS TRP-P0-012 — Transit / Exception management';

    /* ── DEFERRED — named, with the reason and the owner ──────────────── */

    public const DEFERRED = [
        'STOS-REQ-OPS-010' => '"Record delivery" (P0). in_transit → delivered is STT-007, and delivery is SNG-TRN-014 (POD). Q3 ruling: this ticket stops at in_transit.',
        'STOS-REQ-OPS-011' => '"Handle trip cancellation" (P1). No cancelled state exists in Step 9 or Step 11 SM-TRP; inventing one would be the D-9 mistake.',
        'STOS-REQ-OPS-013' => '"Handle driver abandonment/operational incident" (P1). QC-owned, and QC incidents are a separate entity from exceptions — see INCIDENT_IS_NOT_EXCEPTION.',
        'STOS-REQ-PLN-009' => '"Identify vehicle idle due to driver shortage" (P0, FLEET). An automatic exception source owned by Fleet; no idle data exists on the Trip side.',
        'STOS-REQ-MNT-010' => '"Identify overdue maintenance" (P0, FLEET). Automatic source; no maintenance model exists anywhere in the module.',
        'STOS-REQ-TEL-006' => '"Detect temperature excursion" (P0, QC). Automatic source; no telemetry model (SNG-TRN-020, P1).',
        'STOS-REQ-TEL-007' => '"Detect generator OFF during sensitive trip" (P0, QC). Automatic source; no genset model exists.',
    ];

    /* ── Q3 — the state edge this ticket wires ────────────────────────── */

    /**
     * STT-006, LOCKED: dispatched → in_transit | trigger "Dispatch vehicle" |
     * actor TripEngine | precondition "Dispatch confirmed" | side effect
     * "Start monitoring".
     *
     * The precondition became satisfiable only when Record Dispatch shipped on
     * 2026-09-10 — before that, no trip could be "dispatch confirmed" and this
     * edge could not honestly be built. Owner's Q3 ruling, option (b): wire it
     * here, as a MANUAL departure record.
     *
     * Manual because BR-P0-010's trigger is a "GPS event" and there is no GPS
     * (SNG-TRN-020, P1). SM-TRP's entry gate for in_transit is "Departure
     * recorded", which a person can do; "Start monitoring" resolves to this
     * ticket's own exception engine, not to telemetry.
     *
     * Without this edge FRS TRP-P0-011 could never fire — its trigger is
     * literally "Vehicle in transit" — and STOS-REQ-OPS-009 (P0) would be an
     * RTM §50 traceability exception rather than a delivered requirement.
     */
    public const STT_006 = 'STT-006';
    public const STATE_EDGE_OWNED = TripStatus::DISPATCHED.'->'.TripStatus::IN_TRANSIT;

    /** STT-007. Delivery is SNG-TRN-014; nothing here writes `delivered`. */
    public const STT_007 = 'STT-007';
    public const STATE_EDGE_DEFERRED = TripStatus::IN_TRANSIT.'->'.TripStatus::DELIVERED;

    /** The only two columns Q3 permits on transport_trips. */
    public const DEPARTURE_FIELDS = ['departed_at', 'departed_by'];

    /* ── Q1/Q2 — the exception state machine ──────────────────────────── */

    /**
     * Three documents give three different lists, and none is a superset of
     * the others. Recorded as D-29.
     *
     *   Step 9  (authority)   7 states, open → … → verified / closed
     *   SM-EXC  (LOCKED)      3 states: open, acknowledged, resolved
     *   ENUM-004              5 states: adds in_progress, closed
     *   TRP-P0-012            introduces `waived`, which is in none of the three
     *
     * Owner's Q1 ruling: declare Step 9's seven. Owner's Q2 ruling: declare
     * `waived` as well — eight in total — and wire neither it nor the five
     * Step 9 states that Step 11 does not LOCK a transition for.
     *
     * ── Q2 SUPERSEDED 2026-09-18 — D-29 AND D-30 BOTH RULED ─────────────
     * D-29 dissolved without a new decision: the standing Step 9 / Step 11 rule
     * in TEAM-CONTRACTS already answers it. Vocabulary from Step 9, edges from
     * Step 11, and Step 11 contradicting ITSELF resolves too — SM-EXC calling
     * `resolved` terminal is an EDGE claim, ENUM-004 listing `closed` is a
     * VOCABULARY claim, and both are honoured at once.
     *
     * D-30 deferred `waived` the way BR-P0-017's waiver is deferred, and took
     * it OUT of the vocabulary: it is the one status Step 9 does not contain.
     * Seven, not eight.
     */
    public const STATE_RULING_SOURCE = 'Step 9 Master Product Constitution — State_Machines, Exception';
    /**
     * Seven — Step 9's list, and nothing else.
     *
     * It was EIGHT until 2026-09-18, under the owner's Q2 ruling ("waived
     * declared in the enum, not wired"). The standing Step 9 / Step 11 rule
     * supersedes that: the vocabulary comes from Step 9, and `waived` is in FRS
     * and BRWM alone. D-30. The RULINGS array below is left exactly as the
     * owner wrote it — this constant records what the code does now, and the
     * register records why the two differ.
     */
    public const STATE_COUNT_DECLARED = 7;

    public const STT_015 = 'STT-015';   // open → acknowledged
    public const STT_016 = 'STT-016';   // acknowledged → resolved

    /* ── Wired 2026-09-18, once D-29 and D-30 were ruled ──────────────── */

    /**
     * The only source this ships with, and it is API-007's own act.
     *
     * AUTOMATIC_SOURCES below lists every rule that would raise an exception
     * without a person; all three are unreachable. Manual is not a reduced
     * version of automatic — it is what "Raise exception" means.
     */
    public const SOURCE_MANUAL = 'manual';

    /**
     * BR-P0-011's evidence requirement, in the words a refusal uses.
     *
     * The rule: "No critical exception can be marked resolved without
     * resolution evidence." Q4 made the evidence note-only — BR-P0-011 asks for
     * "note/photo/document", and photo and document need file upload, which
     * Transport does not have at all (D-22).
     */
    public const BR_011_EVIDENCE = 'BR-P0-011 requires resolution evidence, and a note is the evidence this build can take (photo and document need file upload, which Transport does not have yet).';

    /**
     * The waiver sentence. D-30, and the same discipline as BR-P0-017's.
     *
     * It says NOT BUILT YET. It must never say or imply that no waiver exists:
     * FRS TRP-P0-012 names `waived` as an outcome and BR-P0-011's override is
     * "Owner waiver", so a screen claiming otherwise is misleading a user about
     * their own rule book.
     */
    public const WAIVER_MESSAGE = 'BR-P0-011 allows an Owner to waive this requirement. That waiver is specified but not built yet, so there is currently no way to resolve an exception without a note.';

    public const WAIVER_DEFERRED = 'FRS TRP-P0-012 names `waived` as an outcome and BR-P0-011 names the Owner role that may exercise it. Specified, not built. Deferred by the owner 2026-09-18 pending a ticket that authorises and audits one — D-30.';

    /* ── OPS §87 — the twelve fields an exception "must contain" ───────── */

    /**
     * 'built'      — a column or a derived value this ticket provides.
     * 'deferred'   — a real requirement with no data model to hang it on.
     */
    public const OPS_87_DISPOSITION = [
        'exception ID'      => 'built',      // exception_number, per-tenant per-year
        'category'          => 'built',      // OPS §88's eight
        'severity'          => 'built',      // ENUM-003 / FLD-014
        'source'            => 'built',      // who or what raised it; manual only today
        'transaction'       => 'built',      // trip_id, and optionally vehicle/driver
        'owner'             => 'built',      // manual assignment — Q6
        'timestamp'         => 'built',      // raised_at
        'due time'          => 'built',      // derived from severity SLA — Q5
        'financial impact'  => 'deferred',   // no cost model on the Trip side (SNG-TRN-012)
        'customer impact'   => 'deferred',   // no customer-impact vocabulary is defined anywhere
        'resolution'        => 'built',      // resolution note — Q4
        'closure'           => 'built',      // resolved_at + resolved_by
    ];

    /** OPS §88's eight categories, verbatim, with the document's own gloss. */
    public const OPS_88_CATEGORIES = [
        'resource'      => 'Driver/vehicle shortage',
        'compliance'    => 'Invalid document',
        'operational'   => 'Delay/deviation',
        'temperature'   => 'Excursion/Genset',
        'financial'     => 'Revenue leakage/billing block',
        'customer'      => 'Complaint/service issue',
        'fleet'         => 'Breakdown/maintenance',
        'documentation' => 'Missing/rejected document',
    ];

    /* ── Automatic creation: declared, and unavailable ────────────────── */

    /**
     * Every rule that would raise an exception without a person, and what each
     * one is actually waiting for. None is reachable, so 013 ships with manual
     * raising only — which is exactly what API-007 ("Raise exception") is.
     */
    public const AUTOMATIC_SOURCES = [
        'BR-P0-008' => 'Fuel variance beyond threshold. Needs SNG-TRN-012 (Cost); not built, and Finance-category ownership is unresolved.',
        'BR-P0-009' => 'Duplicate/mismatched toll reference. Needs SNG-TRN-012.',
        'BR-P0-010' => 'Critical route deviation/idle. Trigger is a "GPS event"; needs SNG-TRN-020 (P1). THIS IS THE TRANSIT RULE, and it is unreachable.',
    ];

    /* ── Q4/Q5/Q6 and the rest, as rulings ────────────────────────────── */

    /**
     * The owner's decisions, in the owner's own words.
     *
     * Verbatim from the approval of 2026-09-10. Nothing in this array is a
     * paraphrase, an inference or an elaboration — the reasoning that surrounds
     * each decision is mine and lives in RULING_RATIONALE, one array down,
     * because a constant named RULINGS that mixes the two misattributes my
     * argument to the person who authorised the work.
     */
    public const RULINGS = [
        'Q1' => "Declare Step 9's full 7-state list plus waived (8 total), wire only Step 11's two LOCKED transitions (open→acknowledged, acknowledged→resolved). Everything else declared and unreachable.",
        'Q2' => 'waived declared in the enum, not wired.',
        'Q3' => 'Option (b) — build the Exception engine, and also wire dispatched → in_transit as a manual "Record departure" action (departed_at, departed_by columns only). Nothing beyond that — no in_transit → delivered, no GPS/telemetry/odometer/temperature, no automatic triggers.',
        'Q4' => 'Closure evidence is note-only for BR-P0-011; photo/document stays deferred (D-22).',
        'Q5' => 'SLA is elapsed wall-clock only, durations per severity in transport_policies; business calendar and escalation notifications deferred (D-34, ticket 021).',
        'Q6' => 'Manual owner assignment only; no auto-ownership (no branch/escalation matrix data model).',
    ];

    /**
     * WHY each ruling is what it is — written by the implementer, not the owner.
     *
     * Kept because a decision without its reasoning is the thing that gets
     * reversed by the next person who sees only the outcome. Kept SEPARATE
     * because it is argument, not authority.
     */
    public const RULING_RATIONALE = [
        'Q1' => 'Step 9 is the authority tier and its list contains every token any registry LOCKS. Declaring all of them and wiring only the two LOCKED transitions is the pattern tickets 009 and 010 already follow.',
        'Q2' => '`waived` appears only in FRS TRP-P0-012 and is BR-P0-011\'s named override, so dropping it would lose the rule\'s only escape hatch. Nothing may waive until a ticket exists that authorises and audits one — the same reasoning that keeps PretripReadiness::OVERRIDE_REQUIRED unwired.',
        'Q3' => 'STT-006\'s precondition is "Dispatch confirmed", which only became satisfiable when Record Dispatch shipped. Without this edge FRS TRP-P0-011 could never fire — its trigger is literally "Vehicle in transit" — and STOS-REQ-OPS-009 (P0) would be an RTM §50 traceability exception rather than a delivered requirement.',
        'Q4' => 'BR-P0-011 asks for "note/photo/document". A note is buildable today; photo and document need file upload, which Transport does not have at all (D-22).',
        'Q5' => 'BRWM §58 requires seven elements for an SLA, one of which is a business calendar, and §59 requires that calendar to model working hours, weekends, holidays, branch and customer. None has an entity (D-34). Wall-clock is the part that can be computed honestly.',
        'Q6' => 'OPS §90 wants owners assigned automatically from category, branch, role, organization and escalation matrix. Branch and the escalation matrix have no data model anywhere in the package, and OPS §91\'s L1..L5 ladder names roles Step 11 does not define (D-31).',
    ];

    /**
     * Choices the implementer made and the owner then approved.
     *
     * These are not answers to Q1..Q6. They are places where the documents are
     * silent and something had to be decided in order to build at all; each was
     * put to the owner explicitly on 2026-09-10 and approved. Recorded here so a
     * later reader can tell a document-derived fact from a judgement call.
     */
    public const DESIGN_DECISIONS = [
        'sla states beyond OPS §104' => 'STOPPED and NONE are added to §104\'s On Track/At Risk/Overdue. A resolved exception has no live clock, and policy may set no SLA at all; reporting either as "On Track" would imply a deadline nobody set.',
        'at-risk threshold'          => '§104 names the state but never says when On Track becomes At Risk. It is a tenant policy expressed as a FRACTION of the SLA window, not a fixed number of minutes — fifteen minutes is meaningless against a fifteen-minute SLA and generous against a day-long one (CMP §10).',
        'category vocabulary'        => 'Step 11 has no category enum although OPS §87 requires the field (D-37). OPS §88\'s eight are used, all eight selectable, because a category is a label a person picks and none needs a data model behind it.',
        'exception numbering'        => 'OPS §87 requires an "exception ID". It follows the module\'s existing shape (TO-YYYY-NNNNNN, TRP-YYYY-NNNNNN) and is allocated through the central Document Numbering Engine, which is the only allocator this codebase permits.',
    ];

    /* ── Excluded, with reasons ───────────────────────────────────────── */

    public const EXCLUDED = [
        'automatic exception creation' => 'See AUTOMATIC_SOURCES — all three rules depend on tickets that are not built (012) or P1 (020).',
        'notifications'                => 'OPS §105 "before breach: warning; at breach: escalation", TRP-P0-012 "WhatsApp/SMS/email", QA-006 "notification triggered". All SNG-TRN-021, P1/Backlog. The SLA state is computed and exposed; nothing is sent.',
        'escalation matrix'            => 'OPS §91 L1 Employee → L5 CEO, "exact timing configurable". No role hierarchy, no branch and no matrix entity exists. Q6.',
        'automatic owner assignment'   => 'OPS §90. Same missing data model as the escalation matrix. Q6.',
        'task creation'                => 'OPS §92/§93 route exceptions into "Sangoe\'s shared Task Engine" and §153 puts "Create Task" in the exception path. That engine is another module; this one must not write to it.',
        'photo/document evidence'      => 'BR-P0-011 asks for "note/photo/document". Transport has no file upload at all (D-22). Q4.',
        'waiver'                       => 'BR-P0-011\'s override is "Owner waiver". Declared as a state, unreachable. Q2. The rule is therefore enforced with NO override path, which is stricter than specified, not weaker.',
        'business calendar'            => 'SLA durations are wall-clock. Working hours, holidays and pauses need a calendar nobody owns (D-34). Q5.',
        'financial impact'             => 'OPS §87 field. Needs SNG-TRN-012 (Cost).',
        'customer impact'              => 'OPS §87 field. No document anywhere defines its values — recording a free-text guess would repeat D-9.',
        'in_transit -> delivered'      => 'STT-007. Delivery confirmation is SNG-TRN-014 (POD), whose dependency DEP-005 is this ticket. Q3 stops at in_transit so 014 inherits an open door rather than a half-built one.',
        'arrived'                      => 'Step 9 puts ARRIVED between IN_TRANSIT and DELIVERED; Step 11 STT-007 goes straight to delivered. The two disagree (D-36) and neither is this ticket\'s to resolve.',
        'GPS / telemetry'              => 'TRP-P0-011\'s GPS position, speed, stop duration, ETA and route rules are SNG-TRN-020 (P1). Only its "manual update fallback" is built.',
        'control room'                 => 'TRP-P0-011 "dashboard highlights actionable exceptions". SNG-TRN-019, P1, and it depends on this ticket.',
    ];

    /**
     * QC incidents and CAPA are a DIFFERENT entity, and must not be merged in.
     *
     * STOS-REQ-QC-001..009 describe complaint → incident → RCA → CAPA →
     * verification, owned by Quality with its own lifecycle. No ticket in the
     * register builds it. An exception links to a trip and carries an SLA; an
     * incident carries a root cause and a corrective action. Collapsing them
     * would invent a model neither document describes.
     */
    public const INCIDENT_IS_NOT_EXCEPTION = 'STOS-REQ-QC-001..009 (incident/RCA/CAPA) are a separate Quality entity with no ticket. Not built, not merged into exceptions.';

    /* ── The rules that bite ──────────────────────────────────────────── */

    /** BR-P0-010 — "Critical route deviation/idle event creates exception and SLA." */
    public const BR_TRANSIT_EXCEPTION = 'BR-P0-010';

    /** BR-P0-011 — "No critical exception can be marked resolved without resolution evidence." */
    public const BR_RESOLUTION_EVIDENCE = 'BR-P0-011';

    /** OPS §154 — an exception may interrupt only when necessary, but must never disappear. */
    public const OPS_154 = 'An exception must interrupt the workflow only when necessary, but it must never disappear from the system.';

    /** QA-006 — "Transit delay: exception created, owner assigned, notification triggered." */
    public const QA_006 = 'QA-006';
}
